### ISSUE TITLE
Cron 下持续 timeout ？而手动执行同样的命令貌似是OK的。。

### ISSUE THREAD

**Issue by nutinshell** [jiehanzheng/squid2radius#3]
```
<open file '/var/log/squid3/access.log.1', mode 'r' at 0x7f71e5da0db0>
Analyzing.............................
Setting up RADIUS server...
Exclusion check has been enabled.
Sending...
xxxx1 2203787..Traceback (most recent call last):
  File "/root/squid2radius/squid2radius.py", line 92, in <module>
    reply = srv.SendPacket(req)
  File "/usr/local/lib/python2.7/dist-packages/pyrad/client.py", line 161, in SendPacket
    return self._SendPacket(pkt, self.acctport)
  File "/usr/local/lib/python2.7/dist-packages/pyrad/client.py", line 147, in _SendPacket
    raise Timeout
pyrad.client.Timeout
<open file '/var/log/squid3/access.log.1', mode 'r' at 0x7f43e80f4db0>
Analyzing...........................
Setting up RADIUS server...
Exclusion check has been enabled.
Sending...
yyyyy2 9393541.Traceback (most recent call last):
  File "/root/squid2radius/squid2radius.py", line 78, in <module>
    reply = srv.SendPacket(req)
  File "/usr/local/lib/python2.7/dist-packages/pyrad/client.py", line 161, in SendPacket
    return self._SendPacket(pkt, self.acctport)
  File "/usr/local/lib/python2.7/dist-packages/pyrad/client.py", line 147, in _SendPacket
    raise Timeout
pyrad.client.Timeout
```

**Comment by nutinshell** [comment]
这个似乎是因为radius服务器mysql阻塞导致，先关了再说。。

**Comment by jiehanzheng** [comment]
大叔是不是所有服务器都 `0 0 * * *` 了？

**Comment by nutinshell** [comment]
大叔还不至于这么蠢= =貌似是日本到美国的问题

**Comment by jiehanzheng** [comment]
lol
